id = "zomorrod-theme"
name = "Zomorrod"
version = "0.0.2"
schema_version = 1
authors = ["Ali Nayreez alinayreez@gmail.com"]
description = "A dark, visually appealing cool theme with an emerald like feel"
repository = "https://github.com/AliNayreez/zomorrod-theme"
